/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AlbumCreate {
  name: string;
  timestamp: string;
  release_time?: string | null;
  event_id: string;
  cover_id?: string | null;
}
