/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhotoReadSingleStub } from './photoReadSingleStub';

export interface AlbumReadList {
  name: string;
  timestamp: string;
  release_time?: string | null;
  event_id: string;
  cover_id?: string | null;
  id: string;
  photos_count: number;
  cover_photo: PhotoReadSingleStub | null;
  hidden_secret: string | null;
  views: number;
}
