/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhotoReadSingleStub } from './photoReadSingleStub';

export interface ModelsPhotoPhotoReadSingleAlbum {
  id: string;
  name: string;
  timestamp: string;
  cover_photo: PhotoReadSingleStub | null;
}
