/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhotoReadList } from './photoReadList';

export interface PhotoStream {
  photos: Array<PhotoReadList>;
  next_photo_id: string;
  next_timestamp: string;
}
