/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelsPhotoPhotoReadSingleAlbum } from './modelsPhotoPhotoReadSingleAlbum';
import { PhotoImgUrls } from './photoImgUrls';
import { PhotoTagRead } from './photoTagRead';
import { Author } from './author';

export interface PhotoReadSingle {
  id: string;
  timestamp: string | null;
  img_urls: PhotoImgUrls;
  upload_processed: boolean;
  uploaded_at: string;
  views: number;
  author: Author;
  exif: { [key: string]: any };
  albums: Array<ModelsPhotoPhotoReadSingleAlbum>;
  gps_thumb: string | null;
  gps_lat: number | null;
  gps_lon: number | null;
  tags?: Array<PhotoTagRead>;
}
