/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhotoUploadPreSignedUrl } from './photoUploadPreSignedUrl';

export interface PhotoUploadResponse {
  photo_id: string;
  pre_signed_url: PhotoUploadPreSignedUrl;
}
