/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhotoImgUrls } from './photoImgUrls';

export interface PhotoReadList {
  id: string;
  timestamp: string | null;
  img_urls: PhotoImgUrls;
  upload_processed: boolean;
  uploaded_at: string;
  views: number;
}
