/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PhotoUploadPreSignedUrlFields } from './photoUploadPreSignedUrlFields';

export interface PhotoUploadPreSignedUrl {
  url: string;
  fields: PhotoUploadPreSignedUrlFields;
}
