/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocationInner } from './locationInner';

export interface ValidationError {
  loc: Array<LocationInner>;
  msg: string;
  type: string;
  input?: any | null;
  ctx?: object;
}
