#!/bin/sh
set -e

############################
# Check generated services #
############################

SERVICES_DIR="src/shared/back-end"
OPENAPI_JSON_PATH="https://api.dev.kick-in.media/openapi.json"

# First generate the hash of the existing files
# Use md5sum as it was found in the environment
OLD_HASH=$(find "$SERVICES_DIR" -type f -exec md5sum {} + | sort -k 2 | md5sum | awk '{ print $1 }')

# Remove all the existing generated files before regenerating
echo "Regenerating API services to compare..."
rm -rf "${SERVICES_DIR:?}"/*

# Generate the API services using openapi-generator-cli
# Using npx to ensure it's available
npx @openapitools/openapi-generator-cli generate -g typescript-angular -o "$SERVICES_DIR" -i "$OPENAPI_JSON_PATH"

# Remove unwanted files generated by the openapi generator
echo "Cleaning up unnecessary generated files..."
rm -rf "$SERVICES_DIR/.openapi-generator"
rm -f "$SERVICES_DIR/.openapi-generator-ignore"
rm -f "$SERVICES_DIR/README.md"
rm -f "$SERVICES_DIR/git_push.sh"
rm -f "$SERVICES_DIR/.gitignore"
rm -f "openapitools.json"

# Compute the hash of the newly generated files
NEW_HASH=$(find "$SERVICES_DIR" -type f -exec md5sum {} + | sort -k 2 | md5sum | awk '{ print $1 }')

# Compare the hashes
if [ "$OLD_HASH" != "$NEW_HASH" ]; then
    echo "Generated API services have changed. Please commit the updated files separately."
    exit 1
else
    echo "Generated API services are up to date."
    exit 0
fi
