name: Add new issues to the issue tracker.

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to the issue tracker.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/kickin-media/projects/1
          github-token: ${{ secrets.ISSUE_TRACKER_PAT }}
