name: Build and Publish

on:
  push:
    branches:
      - master

jobs:

  build-and-push:
    name: Build and publish front-end (${{ matrix.projects.name }}-${{ matrix.projects.environment }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        projects:
          - name: kickin
            environment: dev
          - name: kickin
            environment: prod
          - name: bata
            environment: prod

    environment:
      name: ${{ matrix.projects.name }}-${{ matrix.projects.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build front-end
        run: |
          npm install
          npm run ng -- build ${{ vars.NPM_NAME }}

      - name: Deploy front-end to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private
        env:
          AWS_S3_BUCKET: ${{ matrix.projects.name }}-media-frontend-${{ matrix.projects.environment }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_DEPLOY_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_DEPLOY_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
          SOURCE_DIR: dist/${{ vars.NPM_NAME }}/browser

      - name: Invalidate front-end cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ vars.CLOUDFRONT_DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: "eu-west-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_DEPLOY_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_DEPLOY_AWS_SECRET_ACCESS_KEY }}
