name: Build and Publish

on:
  push:
    branches: [master]

jobs:

  build-and-push:
    name: Build front-end and push to S3
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        environment:
          - dev
          - prod

    environment:
      name: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build front-end
        run: |
          node -v
          yarn install
          REACT_APP_API_ENV=${{ matrix.environment }} yarn run build

      - name: Deploy front-end to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private
        env:
          AWS_S3_BUCKET: kickin-media-frontend-${{ matrix.environment }}
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_DEPLOY_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_DEPLOY_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
          SOURCE_DIR: build

      - name: Invalidate front-end cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: "eu-west-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_DEPLOY_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_DEPLOY_AWS_SECRET_ACCESS_KEY }}
